export const services = [
  {
    id: 'furnished-room-options',
    title: 'Furnished Room Options',
    image: '/room-service.svg',
    sub_header: `We offer a variety of furnished room options to meet your needs. Whether you are looking for a private room or a shared room, we have options for you. Our rooms are fully furnished and include all the amenities you need to feel at home. We also offer flexible lease terms to accommodate your schedule.`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales dui in ante vestibulum, at euismod mi iaculis. Donec urna odio, consectetur nec dictum sit amet, accumsan at enim. Vivamus tristique commodo lectus id tincidunt. Suspendisse dictum dignissim tristique. Nunc sagittis eget risus ultricies faucibus. Vestibulum leo enim, aliquet eu ex a, ornare condimentum ligula.\n\nProin vel iaculis risus, pretium tincidunt urna. Suspendisse potenti. Proin elementum ante eget nibh tincidunt, et vulputate erat pharetra. Phasellus vulputate massa vitae nunc dapibus, vel tempus mi vestibulum. Morbi bibendum mollis dignissim. Quisque sit amet orci ante. Fusce ac ligula odio. Donec tempor massa tristique, ultrices lacus ac, condimentum nisl. Donec sed ligula in purus egestas venenatis. Sed iaculis ex ac lacus efficitur blandit. \n\nIn quis laoreet ex. Maecenas tellus magna, congue nec sagittis non, rhoncus a felis. Etiam sed rutrum sem. Vivamus pellentesque luctus enim, posuere dapibus leo bibendum eget. Proin tincidunt purus eget eros bibendum pellentesque. Suspendisse lobortis scelerisque neque, vel iaculis turpis dictum non. Aliquam varius arcu nec faucibus ullamcorper. Sed eu rutrum elit, ac luctus urna.`,
  },
  {
    id: 'study-and-collaboration-spaces',
    title: 'Study and Collaboration Spaces',
    image: '/study.svg',
    sub_header: `We provide study and collaboration spaces for our residents. Our spaces are designed to help you focus and be productive. Whether you need a quiet place to study or a space to collaborate with others, we have you covered. Our spaces are equipped with high-speed internet and comfortable seating to help you get your work done. We also offer printing and scanning services for your convenience.`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales dui in ante vestibulum, at euismod mi iaculis. Donec urna odio, consectetur nec dictum sit amet, accumsan at enim. Vivamus tristique commodo lectus id tincidunt. Suspendisse dictum dignissim tristique. Nunc sagittis eget risus ultricies faucibus. Vestibulum leo enim, aliquet eu ex a, ornare condimentum ligula.\n\nProin vel iaculis risus, pretium tincidunt urna. Suspendisse potenti. Proin elementum ante eget nibh tincidunt, et vulputate erat pharetra. Phasellus vulputate massa vitae nunc dapibus, vel tempus mi vestibulum. Morbi bibendum mollis dignissim. Quisque sit amet orci ante. Fusce ac ligula odio. Donec tempor massa tristique, ultrices lacus ac, condimentum nisl. Donec sed ligula in purus egestas venenatis. Sed iaculis ex ac lacus efficitur blandit. \n\nIn quis laoreet ex. Maecenas tellus magna, congue nec sagittis non, rhoncus a felis. Etiam sed rutrum sem. Vivamus pellentesque luctus enim, posuere dapibus leo bibendum eget. Proin tincidunt purus eget eros bibendum pellentesque. Suspendisse lobortis scelerisque neque, vel iaculis turpis dictum non. Aliquam varius arcu nec faucibus ullamcorper. Sed eu rutrum elit, ac luctus urna.`,
  },
  {
    id: 'monthly-cleaning-services',
    title: 'Monthly Cleaning Services',
    image: '/cleaning.svg',
    sub_header: `We offer monthly cleaning services to keep our properties looking their best. Our professional cleaning staff will clean your room and common areas to ensure that everything is neat and tidy. We also provide trash removal and recycling services to keep our properties clean and environmentally friendly. Our goal is to provide a clean and comfortable living environment for our residents.`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales dui in ante vestibulum, at euismod mi iaculis. Donec urna odio, consectetur nec dictum sit amet, accumsan at enim. Vivamus tristique commodo lectus id tincidunt. Suspendisse dictum dignissim tristique. Nunc sagittis eget risus ultricies faucibus. Vestibulum leo enim, aliquet eu ex a, ornare condimentum ligula.\n\nProin vel iaculis risus, pretium tincidunt urna. Suspendisse potenti. Proin elementum ante eget nibh tincidunt, et vulputate erat pharetra. Phasellus vulputate massa vitae nunc dapibus, vel tempus mi vestibulum. Morbi bibendum mollis dignissim. Quisque sit amet orci ante. Fusce ac ligula odio. Donec tempor massa tristique, ultrices lacus ac, condimentum nisl. Donec sed ligula in purus egestas venenatis. Sed iaculis ex ac lacus efficitur blandit. \n\nIn quis laoreet ex. Maecenas tellus magna, congue nec sagittis non, rhoncus a felis. Etiam sed rutrum sem. Vivamus pellentesque luctus enim, posuere dapibus leo bibendum eget. Proin tincidunt purus eget eros bibendum pellentesque. Suspendisse lobortis scelerisque neque, vel iaculis turpis dictum non. Aliquam varius arcu nec faucibus ullamcorper. Sed eu rutrum elit, ac luctus urna.`,
  },
  {
    id: 'maintenance-and-support',
    title: '24/7 Maintenance and Support',
    image: '/support.svg',
    sub_header: `We provide 24/7 maintenance and support to address any issues that may arise. Our maintenance staff is available around the clock to handle any repairs or maintenance requests. Whether you have a leaky faucet or a broken appliance, we will take care of it quickly and efficiently. We also offer support services to help you with any questions or concerns you may have. Your comfort and satisfaction are our top priorities. `,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales dui in ante vestibulum, at euismod mi iaculis. Donec urna odio, consectetur nec dictum sit amet, accumsan at enim. Vivamus tristique commodo lectus id tincidunt. Suspendisse dictum dignissim tristique. Nunc sagittis eget risus ultricies faucibus. Vestibulum leo enim, aliquet eu ex a, ornare condimentum ligula.\n\nProin vel iaculis risus, pretium tincidunt urna. Suspendisse potenti. Proin elementum ante eget nibh tincidunt, et vulputate erat pharetra. Phasellus vulputate massa vitae nunc dapibus, vel tempus mi vestibulum. Morbi bibendum mollis dignissim. Quisque sit amet orci ante. Fusce ac ligula odio. Donec tempor massa tristique, ultrices lacus ac, condimentum nisl. Donec sed ligula in purus egestas venenatis. Sed iaculis ex ac lacus efficitur blandit. \n\nIn quis laoreet ex. Maecenas tellus magna, congue nec sagittis non, rhoncus a felis. Etiam sed rutrum sem. Vivamus pellentesque luctus enim, posuere dapibus leo bibendum eget. Proin tincidunt purus eget eros bibendum pellentesque. Suspendisse lobortis scelerisque neque, vel iaculis turpis dictum non. Aliquam varius arcu nec faucibus ullamcorper. Sed eu rutrum elit, ac luctus urna.`,
  },
  {
    id: 'utility-and-internet-inclusion',
    title: 'Utility and Internet Inclusion',
    image: '/internet.svg',
    sub_header: `We include utilities and internet in your rent to make your life easier. You won't have to worry about setting up accounts or paying multiple bills. We take care of everything for you. Our properties are equipped with high-speed internet and all the utilities you need to live comfortably. You can enjoy the convenience of all-inclusive living without any extra hassle.`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales dui in ante vestibulum, at euismod mi iaculis. Donec urna odio, consectetur nec dictum sit amet, accumsan at enim. Vivamus tristique commodo lectus id tincidunt. Suspendisse dictum dignissim tristique. Nunc sagittis eget risus ultricies faucibus. Vestibulum leo enim, aliquet eu ex a, ornare condimentum ligula.\n\nProin vel iaculis risus, pretium tincidunt urna. Suspendisse potenti. Proin elementum ante eget nibh tincidunt, et vulputate erat pharetra. Phasellus vulputate massa vitae nunc dapibus, vel tempus mi vestibulum. Morbi bibendum mollis dignissim. Quisque sit amet orci ante. Fusce ac ligula odio. Donec tempor massa tristique, ultrices lacus ac, condimentum nisl. Donec sed ligula in purus egestas venenatis. Sed iaculis ex ac lacus efficitur blandit. \n\nIn quis laoreet ex. Maecenas tellus magna, congue nec sagittis non, rhoncus a felis. Etiam sed rutrum sem. Vivamus pellentesque luctus enim, posuere dapibus leo bibendum eget. Proin tincidunt purus eget eros bibendum pellentesque. Suspendisse lobortis scelerisque neque, vel iaculis turpis dictum non. Aliquam varius arcu nec faucibus ullamcorper. Sed eu rutrum elit, ac luctus urna.`,
  },
  {
    id: 'community-events-and-workshops',
    title: 'Community Events and Workshops',
    image: '/community.svg',
    sub_header: `We host community events and workshops to bring our residents together and create a sense of community. Our events are designed to help you meet your neighbors and make new friends. We also offer workshops on a variety of topics to help you learn new skills and grow as an individual. Our goal is to create a welcoming and inclusive community where everyone feels at home.`,
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales dui in ante vestibulum, at euismod mi iaculis. Donec urna odio, consectetur nec dictum sit amet, accumsan at enim. Vivamus tristique commodo lectus id tincidunt. Suspendisse dictum dignissim tristique. Nunc sagittis eget risus ultricies faucibus. Vestibulum leo enim, aliquet eu ex a, ornare condimentum ligula.\n\nProin vel iaculis risus, pretium tincidunt urna. Suspendisse potenti. Proin elementum ante eget nibh tincidunt, et vulputate erat pharetra. Phasellus vulputate massa vitae nunc dapibus, vel tempus mi vestibulum. Morbi bibendum mollis dignissim. Quisque sit amet orci ante. Fusce ac ligula odio. Donec tempor massa tristique, ultrices lacus ac, condimentum nisl. Donec sed ligula in purus egestas venenatis. Sed iaculis ex ac lacus efficitur blandit. \n\nIn quis laoreet ex. Maecenas tellus magna, congue nec sagittis non, rhoncus a felis. Etiam sed rutrum sem. Vivamus pellentesque luctus enim, posuere dapibus leo bibendum eget. Proin tincidunt purus eget eros bibendum pellentesque. Suspendisse lobortis scelerisque neque, vel iaculis turpis dictum non. Aliquam varius arcu nec faucibus ullamcorper. Sed eu rutrum elit, ac luctus urna.`,
  },
];
